language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python APIablee/manage.py makemigrations
  - python APIablee/manage.py migrate
  - coverage run --source=. APIablee/manage.py test api

# run coveralls after successful tests
after_success:
- coveralls
